// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utcmasenqtmhvifiugec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0Y21hc2VucXRtaHZpZml1Z2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyOTIzNzgsImV4cCI6MjA2MTg2ODM3OH0.Uuz00PKuHdZYD38W9r4l9rDtC_RKhcqjRCb59x3V6pQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);